data2 = [
    {"name": "insta", "followers": "346", "description": "socialdata"},
    {"name": "twitter", "followers": "210", "description": "socialdata"},
    {"name": "facebook", "followers": "500", "description": "socialdata"},
    {"name": "linkedin", "followers": "150", "description": "professional network"},
    {"name": "snapchat", "followers": "300", "description": "socialdata"},
    {"name": "youtube", "followers": "1000", "description": "videos"},
    {"name": "pinterest", "followers": "220", "description": "ideas"},
    {"name": "reddit", "followers": "480", "description": "forums"},
    {"name": "tiktok", "followers": "900", "description": "short videos"},
    {"name": "github", "followers": "130", "description": "developers"},
    {"name": "stackoverflow", "followers": "90", "description": "developers"},
    {"name": "quora", "followers": "75", "description": "QnA"},
    {"name": "medium", "followers": "180", "description": "blogging"},
    {"name": "spotify", "followers": "800", "description": "music"},
    {"name": "applemusic", "followers": "700", "description": "music"},
    {"name": "netflix", "followers": "1200", "description": "entertainment"},
    {"name": "hulu", "followers": "600", "description": "entertainment"},
    {"name": "primevideo", "followers": "550", "description": "entertainment"},
    {"name": "zoom", "followers": "400", "description": "meetings"},
    {"name": "slack", "followers": "270", "description": "work chat"},
    {"name": "discord", "followers": "390", "description": "gaming chat"},
    {"name": "telegram", "followers": "560", "description": "messaging"},
    {"name": "whatsapp", "followers": "1100", "description": "messaging"},
    {"name": "wechat", "followers": "950", "description": "messaging"},
    {"name": "tinder", "followers": "420", "description": "dating"},
    {"name": "bumble", "followers": "380", "description": "dating"},
    {"name": "okcupid", "followers": "340", "description": "dating"},
    {"name": "duolingo", "followers": "260", "description": "learning"},
    {"name": "coursera", "followers": "330", "description": "learning"},
    {"name": "udemy", "followers": "310", "description": "learning"},
    {"name": "edx", "followers": "290", "description": "learning"},
    {"name": "airbnb", "followers": "620", "description": "travel"},
    {"name": "uber", "followers": "710", "description": "travel"},
    {"name": "lyft", "followers": "690", "description": "travel"},
    {"name": "swiggy", "followers": "580", "description": "food delivery"},
    {"name": "zomato", "followers": "570", "description": "food delivery"},
    {"name": "doordash", "followers": "560", "description": "food delivery"},
    {"name": "flipkart", "followers": "800", "description": "shopping"},
    {"name": "amazon", "followers": "1500", "description": "shopping"},
    {"name": "myntra", "followers": "480", "description": "shopping"},
    {"name": "nike", "followers": "440", "description": "shopping"},
    {"name": "adidas", "followers": "430", "description": "shopping"},
    {"name": "tesla", "followers": "520", "description": "cars"},
    {"name": "ford", "followers": "510", "description": "cars"},
    {"name": "mercedes", "followers": "500", "description": "cars"},
    {"name": "bmw", "followers": "495", "description": "cars"},
    {"name": "ferrari", "followers": "480", "description": "cars"},
    {"name": "lamborghini", "followers": "470", "description": "cars"},
    {"name": "paypal", "followers": "610", "description": "payments"},
    {"name": "stripe", "followers": "590", "description": "payments"}
]
